name: 自动构建
on:
  push:
    branches:
      - master

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Env
        uses: actions/setup-node@v3
        with: 
          node-version: 22
          cache: 'yarn'
          
      - name: Install Pkgs
        run: yarn install --frozen-lockfile
        
      - name: Get Version
        run: node -p -e '`VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
        
      - name: Build
        run: yarn run android
